// webapp/src/components/ComparePanel.jsx
import React, { useState, useRef, useEffect } from "react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, ReferenceLine } from "recharts";
import PhyloTree from "./PhyloTree.jsx";

export default function ComparePanel({ data, sessionA, sessionB }) {
  const [tab, setTab] = useState("sequence");

  if (!data) {
    return (
      <div className="card">
        <div className="card-title">Compare Proteins</div>
        <div style={{ color: "var(--text-2)", fontSize: "0.85rem" }}>
          Upload a <code>comparison.json</code> file (generated by <code>python pdu.py compare</code>) to enable comparison view.
        </div>
      </div>
    );
  }

  const structuralAvailable = data.structural?.available !== false;

  return (
    <div className="card">
      <div className="card-title">
        Comparing {data.protein_a} vs {data.protein_b} · {data.cluster}
      </div>
      <div className="tab-bar">
        <button className={`tab ${tab === "sequence" ? "active" : ""}`} onClick={() => setTab("sequence")}>Sequence</button>
        <button className={`tab ${tab === "phylogenetic" ? "active" : ""}`} onClick={() => setTab("phylogenetic")}>Phylogenetic</button>
        <button
          className={`tab ${tab === "structural" ? "active" : ""}`}
          onClick={() => structuralAvailable && setTab("structural")}
          title={!structuralAvailable ? "Structural comparison requires experimental PDB structures for both proteins." : undefined}
          style={{ opacity: structuralAvailable ? 1 : 0.4, cursor: structuralAvailable ? "pointer" : "not-allowed" }}
        >
          Structural {!structuralAvailable && "⚠"}
        </button>
      </div>
      {!structuralAvailable && tab === "structural" && (
        <div className="error-banner" style={{ marginBottom: "1rem" }}>
          Structural comparison requires experimental PDB structures for both proteins.
        </div>
      )}

      {tab === "sequence" && <SequenceTab data={data} conservationA={sessionA?.conservation} conservationB={sessionB?.conservation} />}
      {tab === "phylogenetic" && <PhyloTab data={data} alignment={sessionA?.alignment} />}
      {tab === "structural" && structuralAvailable && <StructuralTab data={data} />}
    </div>
  );
}

function SequenceTab({ data, conservationA, conservationB }) {
  const { sequence, protein_a, protein_b } = data;
  const conservData = conservationA || conservationB;
  const conservLabel = conservationA ? protein_a : protein_b;
  return (
    <div>
      <div style={{ display: "flex", gap: "2rem", marginBottom: "1.5rem" }}>
        <Stat label="Pairwise Identity" value={`${(sequence.pairwise_identity * 100).toFixed(1)}%`} />
        <Stat label="Pairwise Similarity" value={`${(sequence.pairwise_similarity * 100).toFixed(1)}%`} />
      </div>
      <AlignedDiff alignedA={sequence.aligned_a} alignedB={sequence.aligned_b} labelA={protein_a} labelB={protein_b} />
      {conservData && (
        <div style={{ marginTop: "1.5rem" }}>
          <div style={{ color: "var(--text-2)", fontSize: "0.75rem", marginBottom: "0.5rem" }}>
            Conservation — {conservLabel}
            {!(conservationA && conservationB) && (
              <span style={{ marginLeft: "0.75rem", color: "var(--accent-am)" }}>
                (upload {!(conservationA) ? protein_a : protein_b} conservation.json to overlay both)
              </span>
            )}
          </div>
          <ResponsiveContainer width="100%" height={160}>
            <BarChart data={conservData.residues}>
              <XAxis dataKey="position" tick={{ fill: "var(--text-2)", fontSize: 9 }} interval="preserveStartEnd" />
              <YAxis domain={[0, 1]} tick={{ fill: "var(--text-2)", fontSize: 9 }} />
              <Tooltip
                contentStyle={{ background: "var(--card)", border: "1px solid var(--border)", fontSize: "0.8rem" }}
                formatter={v => [v.toFixed(3), "mutability"]}
              />
              <Bar dataKey="mutability" fill="var(--accent)" radius={[1, 1, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      )}
    </div>
  );
}

function AlignedDiff({ alignedA, alignedB, labelA, labelB }) {
  if (!alignedA || !alignedB) return null;
  const chars = alignedA.split("").map((aa, i) => ({ aa, other: alignedB[i], match: aa === alignedB[i] }));
  const chunkSize = 60;
  const chunks = [];
  for (let i = 0; i < chars.length; i += chunkSize) chunks.push(chars.slice(i, i + chunkSize));

  return (
    <div style={{ fontFamily: "monospace", fontSize: "11px", overflowX: "auto" }}>
      {chunks.map((chunk, ci) => (
        <div key={ci} style={{ marginBottom: "0.75rem" }}>
          <div style={{ color: "var(--text-2)", marginBottom: "2px" }}>{labelA.slice(0, 10).padEnd(12)}{chunk.map(c => c.aa).join("")}</div>
          <div style={{ color: "var(--text-2)", marginBottom: "2px", paddingLeft: "12ch" }}>
            {chunk.map((c, i) => <span key={i} style={{ color: c.match ? "var(--text-2)" : "transparent" }}>|</span>)}
          </div>
          <div style={{ marginBottom: "2px" }}>{labelB.slice(0, 10).padEnd(12)}
            {chunk.map((c, i) => (
              <span key={i} style={{ color: c.match ? "var(--text)" : "var(--accent-am)" }}>{c.other}</span>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

function PhyloTab({ data, alignment }) {
  const { phylogenetic, protein_a, protein_b } = data;
  return (
    <div>
      <div style={{ display: "flex", gap: "2rem", flexWrap: "wrap", marginBottom: "1rem" }}>
        <Stat label="Tree Distance" value={phylogenetic.tree_distance >= 0 ? phylogenetic.tree_distance.toFixed(4) : "N/A"} />
        <Stat label="Shared Cluster" value={`${(phylogenetic.shared_cluster_fraction * 100).toFixed(1)}%`} />
        <Stat label="LCA Node" value={phylogenetic.lca_node} />
      </div>
      <div style={{ color: "var(--text-2)", fontSize: "0.8rem", marginBottom: "0.75rem" }}>
        Tree distance: branch-length sum between {protein_a} and {protein_b} in the NJ tree.
        Shared cluster: fraction of the LCA clade&apos;s leaves that include both proteins.
      </div>
      {alignment?.newick
        ? <PhyloTree data={alignment} />
        : <div style={{ color: "var(--text-2)", fontSize: "0.8rem" }}>
            Upload <code>{protein_a}_tree.json</code> (alignment schema) to see the tree visualization.
          </div>
      }
    </div>
  );
}

function StructuralTab({ data }) {
  const { structural, protein_a, protein_b } = data;
  const viewerRef = useRef(null);
  const [viewerReady, setViewerReady] = useState(false);

  useEffect(() => {
    if (!viewerRef.current || !window.$3Dmol || !structural.pdb_a || !structural.pdb_b) return;
    const viewer = window.$3Dmol.createViewer(viewerRef.current, { backgroundColor: "#080c14" });
    Promise.all([
      fetch(`https://files.rcsb.org/download/${structural.pdb_a}.pdb`).then(r => r.text()),
      fetch(`https://files.rcsb.org/download/${structural.pdb_b}.pdb`).then(r => r.text()),
    ]).then(([pdbA, pdbB]) => {
      viewer.addModel(pdbA, "pdb");
      viewer.setStyle({ model: 0 }, { cartoon: { color: "var(--accent)" } });
      viewer.addModel(pdbB, "pdb");
      viewer.setStyle({ model: 1 }, { cartoon: { color: "var(--accent-am)" } });
      viewer.zoomTo();
      viewer.render();
      setViewerReady(true);
    });
    return () => viewer.clear();
  }, [structural.pdb_a, structural.pdb_b]);

  return (
    <div>
      <div style={{ display: "flex", gap: "2rem", marginBottom: "1.5rem", flexWrap: "wrap" }}>
        <Stat label="TM-score" value={structural.tm_score?.toFixed(3) ?? "—"} />
        <Stat label="Global RMSD (Å)" value={structural.rmsd_global?.toFixed(2) ?? "—"} />
        <Stat label="Reference PDB" value={structural.pdb_a ?? "—"} />
        <Stat label="Query PDB" value={structural.pdb_b ?? "—"} />
      </div>
      {structural.pdb_a && structural.pdb_b && (
        <>
          <div style={{ fontSize: "0.75rem", color: "var(--text-2)", marginBottom: "0.5rem" }}>
            <span style={{ color: "var(--accent)" }}>Teal = {protein_a}</span>
            {" · "}
            <span style={{ color: "var(--accent-am)" }}>Amber = {protein_b}</span>
            {" (structures overlaid by chain A residue numbering)"}
          </div>
          <div ref={viewerRef} style={{ width: "100%", height: "400px", borderRadius: "8px", background: "#080c14" }} />
        </>
      )}
      {structural.alignment_map?.length > 0 && (
        <div style={{ marginTop: "1.5rem" }}>
          <div style={{ color: "var(--text-2)", fontSize: "0.75rem", marginBottom: "0.5rem" }}>
            Per-residue RMSD (Å) along aligned sequence
          </div>
          <ResponsiveContainer width="100%" height={200}>
            <BarChart data={structural.alignment_map.map(m => ({ pos: m.ref_resnum, rmsd: +m.rmsd.toFixed(3) }))}>
              <XAxis dataKey="pos" tick={{ fill: "var(--text-2)", fontSize: 9 }} interval="preserveStartEnd" />
              <YAxis tick={{ fill: "var(--text-2)", fontSize: 9 }} />
              <Tooltip
                contentStyle={{ background: "var(--card)", border: "1px solid var(--border)", fontSize: "0.8rem" }}
                formatter={v => [`${v} Å`, "RMSD"]}
              />
              <Bar dataKey="rmsd" fill="var(--accent-am)" radius={[2, 2, 0, 0]} />
              <ReferenceLine y={structural.rmsd_global} stroke="var(--text-2)" strokeDasharray="4 2"
                label={{ value: "global avg", position: "insideTopRight", fill: "var(--text-2)", fontSize: 9 }} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      )}
    </div>
  );
}

function Stat({ label, value }) {
  return (
    <div style={{ background: "var(--surface)", borderRadius: "8px", padding: "0.75rem 1.25rem", minWidth: "120px" }}>
      <div style={{ color: "var(--text-2)", fontSize: "0.7rem", marginBottom: "0.25rem", textTransform: "uppercase" }}>{label}</div>
      <div style={{ fontSize: "1.1rem", fontWeight: 600, color: "var(--accent)" }}>{value}</div>
    </div>
  );
}
